runtime: java11
#env: standard

instance_class: F1

env_variables:
  spring-boot.run.profiles: 'dev'
#runtime_config:
#  jdk: openjdk8
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#resources:
#  cpu: 2
#  memory_gb: 2
#  disk_size_gb: 10
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5
#manual_scaling:
#  instances: 1